name = "OMBackend"
uuid = "9400bd5f-7561-42f6-8760-03756753da50"
authors = ["JKRT <johti17@liu.se>", "Karim Abdelhak <karim.abdelhak@fh-bielefeld.de>", "AnHeuermann <andreas.heuermann@fh-bielefeld.de>"]
version = "0.1.0"

[deps]
Absyn = "ce2f92e2-a952-11e9-0543-8b443f216f1d"
ExportAll = "ad2082ca-a69e-11e9-38fa-e96309a31fe4"
MetaModelica = "9d7f2a79-07b5-5542-8b19-c0100dda6b06"
